---
- name: install reflector
  pacman:
    name: "reflector"
    update_cache: yes

- name: get faster mirrors to mirrorlist
  command: "reflector --latest {{ reflector.num_mirrors }} --country {{ reflector.country }} --protocol {{ reflector.protocol }} --sort rate --save /etc/pacman.d/mirrorlist"
  
- name: get existing kernel version
  command: "pacman -Q linux"
  register: _old_kernel

- name: update system
  pacman:
    upgrade: yes
    
- name: get new kernel version
  command: "pacman -Q linux"
  register: _new_kernel
  
- name: reboot
  shell: sleep 5 && /sbin/shutdown -r
  async: 0
  poll: 0
  when: "_old_kernel.stdout != _new_kernel.stdout"

- name: wait for arch_box to reboot
  wait_for_connection:
    delay: 60
    timeout: 600
  
- name: install essential packages
  command: "pacman -S --noconfirm --noprogressbar --needed {{ packages.essential | join(' ') }}"
  
- name: check if yay is installed
  stat: 
    path: "/usr/bin/yay"
  register: _yay_result

- import_tasks: yay.yml
  when: _yay_result.stat.exists == False
  
- name: install pacman packages
  command: "pacman -S --noconfirm --noprogressbar --needed {{ packages.all | join(' ') }}"

- name: install yay packages
  command: "yay -S --noconfirm --needed {{ packages.aur | join(' ') }}"
  become: yes
  become_user: "{{ user.username }}"
