---
- name: add user to additional groups
  user:
    name: "{{ user.username }}"
    append: yes
    groups: "{{ user.additional_groups }}"
    
- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: set makeflags for faster compilation
  lineinfile:
    dest: "/etc/makepkg.conf"
    line: 'MAKEFLAGS="-j$(nproc)"'

- name: use pixz instead of xz
  lineinfile:
    dest: "/etc/makepkg.conf"
    line: "COMPRESSXZ=(pixz)"
    regexp: '^COMPRESSXZ'

- name: use pigz instead of gz
  lineinfile:
    dest: "/etc/makepkg.conf"
    line: "COMPRESSGZ=(pigz -c -f -n)"
    regexp: '^COMPRESSGZ'

- name: set journald log size
  lineinfile:
    dest: "{{ tweaks.journald.path }}"
    line: "SystemMaxUse={{ tweaks.journald.size }}"
    regexp: "^#SystemMaxUse"

- name: change IO scheduler
  command: "echo noop > /sys/block/sda/queue/scheduler"

- name: generate .bashrc
  template:
    src: bashrc.j2
    dest: "{{ bash.config_file }}"
  become: yes
  become_user: "{{ user.username }}"

- name: really add options to fstab
  mount:
    name: "{{ item.mount }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},{{ fstab.options | join(',') }}"
    state: present
  with_items: "{{ ansible_mounts }}"
  register: _fstab

- name: "If mountpoint was changed, remount"
  command: "mount -o remount {{ item.mount }}"
  when: _fstab.changed
  with_items: "{{ ansible_mounts }}"
  warn: false
